### PR TITLE
overview/foundations.md: spelling/typos

### PR DESCRIPTION
**Pull request by NReilingh**
"outermost" is [one word](https://www.google.com/search?client=safari&rls=en&q=outermost)

### CODE REVIEW

**Comment by verdverm** [comment]
If you want to accumulate any more you find into a single PR, I can wait to merge them

**Comment by NReilingh** [comment]
@verdverm Would you prefer that? I usually just PR as I go through a doc and find stuff, but I'm happy to collect and PR all at once if that works better for you.

**Comment by NReilingh** [comment]
(And apologies for the half-dozen additional PRs I've submitted before reading this if so!)

**Comment by verdverm** [comment]
either or, whatever makes it easiest for you to contribute!

**Pull request merged**
